//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouringApp.Models.TO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfil
    {
        public Perfil()
        {
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public int PerfilID { get; set; }
        public string Perfil1 { get; set; }
    
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
