//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouringApp.Models.TO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Cartillas = new HashSet<Cartilla>();
        }
    
        public int UsuarioID { get; set; }
        public string DNI { get; set; }
        public string Contraseña { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public int PerfilID { get; set; }
    
        public virtual ICollection<Cartilla> Cartillas { get; set; }
        public virtual Perfil Perfil { get; set; }
    }
}
